### ISSUE TITLE
MOI in meta data

### ISSUE THREAD

**Issue by JiaxinLi-lipluszn** [klarman-cell-observatory/Perturb-CITE-seq#3]
I have a naive question about the MOI column in RNA_metadata.csv.
I downloaded files on single cell portal and saw there is a column of MOI in RNA_metadata.csv file. For each cell there is an interger MOI. I wonder how is the MOI for each cell measured.
I remember I read in the paper that the MOI is an experiment condition, where the MOI is set to 0.1.
<img width="559" alt="Screen Shot 2021-08-12 at 4 01 10 PM" src="https://user-images.githubusercontent.com/69056971/129269514-b5827ae0-a787-49ff-bb1b-e6bc6a777fe7.png">

**Comment by CFrangieh** [comment]
MOI in RNA_metadata.csv is calculated as the number of sgRNAs detected in each cell from the dial-out PCR. The highlighted region you are referring to refers to the viral titer when infecting cells with Cas9 virus prior to selection and sequencing. We transduce at a low MOI (0.1) to ensure the majority of cells are not transduced and the majority of cells that are transduced only have 1 insertion. After antibiotic selection, only cells with an insertion will continue to grow, and the majority of these cells will only have one insertion (with some probability cells can still have multiple insertions). These are the cells we sequence and use for our dial-out PCR to calculate the MOI in RNA_metadata.csv
